version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  pyspark:
    image: bitnami/spark:3.5
    container_name: pyspark
    depends_on:
      - kafka
    ports:
      - "4040:4040"
    environment:
      - SPARK_MODE=client
      - HOME=/home/sparkuser
    user: root # Jalankan sebagai root agar bisa buat user baru
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash -c "useradd -m sparkuser && export HOME=/home/sparkuser && su - sparkuser -c 'tail -f /dev/null'"
